# Generated by Django 2.0.2 on 2020-05-05 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0003_auto_20200505_1221'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='quentity',
        ),
        migrations.AddField(
            model_name='cart',
            name='quantity',
            field=models.IntegerField(default=0),
        ),
    ]
