# Generated by Django 2.0.2 on 2020-05-06 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0005_auto_20200505_2036'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartdatabase',
            name='price',
            field=models.CharField(default='', max_length=100),
        ),
    ]
