# Generated by Django 2.0.2 on 2020-05-06 15:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0006_cartdatabase_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartdatabase',
            name='price',
        ),
    ]
