# Generated by Django 2.0.2 on 2020-05-08 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0007_remove_cartdatabase_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartdatabase',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
    ]
