# Generated by Django 2.0.2 on 2020-04-20 15:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='procategory',
            new_name='Category',
        ),
        migrations.RenameModel(
            old_name='Women',
            new_name='Product',
        ),
    ]
