# Generated by Django 2.0.2 on 2020-04-23 06:37

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='sizes',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('XL', 'XL'), ('XXL', 'XXL'), ('SM', 'SMALL'), ('LG', 'LARGE'), ('MD', 'MEDIUM')], default='', max_length=15),
        ),
    ]
